name: Sync Fork

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the fork
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: false

      - name: Set up master branch
        run: |
          git checkout master
          git reset --hard origin/master

      - name: Add upstream remote
        run: |
          git remote get-url upstream || git remote add upstream https://github.com/Skatteetaten/trekktabell.git
          git fetch upstream

      - name: Rebase main onto upstream/main
        run: |
          git rebase upstream/master || git rebase --abort
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} master --force-with-lease