name: Sync Fork

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: false
          clean: true

      - name: Set up master branch
        run: |
          git checkout master
          git reset --hard origin/master

      - name: Print current HEAD and remotes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          echo "HEAD: $(git rev-parse HEAD)"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${REPO}.git
          git fetch origin master
          echo "Origin/master: $(git rev-parse origin/master)"
          git log --oneline --graph --decorate --all -n 10

      - name: Add upstream remote
        run: |
          git remote get-url upstream || git remote add upstream https://github.com/Skatteetaten/trekktabell.git
          git fetch upstream

      - name: Rebase main onto upstream/main
        run: |
          git rebase upstream/master || git rebase --abort
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} master --force-with-lease