name: Sync Fork

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  rebase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the fork
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: false

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/Skatteetaten/trekktabell.git
          git fetch upstream

      - name: Rebase main onto upstream/main
        run: |
          git checkout master
          git rebase upstream/master || git rebase --abort
          git push origin master --force-with-lease
